/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Person } from './person';

/**
 * 
 * @export
 * @interface Achievement
 */
export interface Achievement {
    /**
     * 
     * @type {number}
     * @memberof Achievement
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Achievement
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof Achievement
     */
    'date'?: string;
    /**
     * 
     * @type {string}
     * @memberof Achievement
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof Achievement
     */
    'image'?: string;
    /**
     * 
     * @type {Person}
     * @memberof Achievement
     */
    'person'?: Person;
}

