/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Person } from './person';
// May contain unused imports in some cases
// @ts-ignore
import { Place } from './place';

/**
 * 
 * @export
 * @interface Presence
 */
export interface Presence {
    /**
     * 
     * @type {number}
     * @memberof Presence
     */
    'id'?: number;
    /**
     * 
     * @type {Person}
     * @memberof Presence
     */
    'person'?: Person;
    /**
     * 
     * @type {Place}
     * @memberof Presence
     */
    'place'?: Place;
    /**
     * 
     * @type {string}
     * @memberof Presence
     */
    'start'?: string;
    /**
     * 
     * @type {string}
     * @memberof Presence
     */
    'end'?: string;
}

